// <auto-generated />
namespace Vizew.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class step64 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(step64));
        
        string IMigrationMetadata.Id
        {
            get { return "201905160830039_step64"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
